### ISSUE TITLE
Druhý domácí úkol

### ISSUE THREAD

**Issue by martinamickova** [martinamickova/kurz-python-czechitas#2]

**Comment by srpwnd** [comment]
Ahoj Martino,

skvěle zpracovaný úkol. Líbí se mi, jak je kód kompaktní a srozumitelný. Jediné čemu bych se snažil vyvarovat je pojmenovávání proměnných názvy jako `i`, `x`, `y`, a to i v cyklech.

Označuji úkol za splněný 💪
